{% set name = "transfocate" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/transfocate/archive/v{{ version }}.tar.gz
  sha256: 2373eb3eefe5963e374f1d061af35854d1ce641469effa207019a24af335cbaf

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - bluesky
    - databroker
    - numpy
    - openpyxl
    - ophyd >=1.5.0
    - pandas
    - pcdsdevices >=4.0.0
    - prettytable
    - reportlab

test:
  imports:
    - transfocate
    - transfocate.automated_checkout

about:
  home: https://github.com/pcdshub/transfocate
  doc_url: https://pcdshub.github.io/transfocate/
  dev_url: https://github.com/pcdshub/transfocate
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md
  summary: 'Compound refractive lens (CRL) transfocator device library'

extra:
  recipe-maintainers:
    - klauer
    - zllentz
    - zrylettc
